version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - tinyllama_volume_test:/root/.ollama
    networks:
      - myflask-app-network
      # This is the GPU configuration for the ollama service
      # comment this section if you don't want to use GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  backend:
    image: tarakdhieb7/fis_localai_backend:latest 
    container_name: fis-localai-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - myflask-app-network

  front-end: 
    image: tarakdhieb7/fis_localai_frontend:latest
    container_name: fis-localai-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - myflask-app-network

volumes:
  tinyllama_volume_test:
    name: tinyllama_volume_test

networks:
  myflask-app-network:
    name: myflask-app-network
    driver: bridge