version: '3.8'

services:
  ollama_test:
    image: ollama/ollama:latest
    container_name: ollama_test
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - tinyllama_volume:/root/.ollama
    networks:
      - myflask-app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama_test
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama_test:11434
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - myflask-app-network

  front-end-test:
    image: front-end:latest
    container_name: front-end-test
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - myflask-app-network

volumes:
  tinyllama_volume:
    name: tinyllama_volume

networks:
  myflask-app-network:
    name: myflask-app-network
    driver: bridge